### PR TITLE
First functional tests using the PageObject pattern

### PR DESCRIPTION
**Pull request by staal-it**
First functional tests using the PageObject pattern https://martinfowler.com/bliki/PageObject.html

### CODE REVIEW

**Comment by jfversluis** [comment]
Looking amazing, thanks!
How do I run this? Is this simply triggered by `dotnet test`? Nothing fancy? Or do I need a special build task for it?

**Comment by jfversluis** [comment]
Yep! Already did! Thanks :)

**Comment by faniereynders** [comment]
We should investigate to rather use xUnit instead :)

**Comment by staal-it** [comment]
How does one re-run the CI build and merge the changes?

**Comment by faniereynders** [comment]
I'm not sure I follow, please elaborate?

**Pull request merged**
