### PR TITLE
Updated NuGet packages

### PR DESCRIPTION
**Pull request by rickvdbosch**

### CODE REVIEW

**Comment by jfversluis** [comment]
Hm build seems to fail but doesn't seem related to this but more that something is wrong with the pipeline or version numbers?

**Comment by rickvdbosch** [comment]
Not sure about that one @jfversluis. the build runs locally, but I see the issue concerns code coverage:

```
Failed to initialize code coverage datacollector with error: System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.TestPlatform.Utilities.CodeCoverageRunSettingsProcessor' from assembly 'Microsoft.TestPlatform.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Will run locally and see if it has something to do with the updated packages.

**Comment by rickvdbosch** [comment]
Just ran the exact same `dotnet test` command (except for locations, obviously) locally on this branch, and it worked fine. The issue doesn't seem to be connected to the NuGet package update.

**Comment by jfversluis** [comment]
The only thing I can think of is that the updated packages in the test projects to something that is not supported (yet) on the hosted build agents?

**Comment by rickvdbosch** [comment]
Hmm... tried the 'fix' I used on the other branch but doesn't seem to work over here. 🤔
Will investigate further.

**Comment by rickvdbosch** [comment]
I'm going to restart the package update since this doesn't seem to want to work. 😕

**Pull request closed without merging**
