### PR TITLE
Extract event images

### PR DESCRIPTION
**Pull request by Jandev**
As described in #10 

Added ARM template to set up the complete environment, Storage, App Services, SQL Server, Service Bus, Storage Container, Key Vault, etc.

Whenever a CFP is stored, I'm posting a message to the ServiceBus Queue. This message is then picked up by an Azure Function with a nice trigger on it. This Function will download the Event Image, specified in the `EventImageUrl`, put it in the storage container (using Blob output binding). Afterwards it will update the appropriate record in the database with the new URL.

I've tested the sending a message to the servicebus locally a while back and this appears to be working. Also tested the Azure Function and this one appears to be working also.

However, I can't seem to get the site working now due to some errors in the migrations. It looks like there are some incompatible migrations when starting from scratch. Deleting the database and run the `Update-Database` command appears to be failing for some reason. Maybe something to check out, or create a new issue for?

### CODE REVIEW

**Comment by jfversluis** [comment]
Awesome stuff! I really, really need to get that ARM stuff working... I will check out the db issue!

**Comment by Jandev** [comment]
For your CI/CD convenience, I've created a few screenshots which might help setting you up those ARM thingies 😄 

Step 1: Make sure the ARM template is being deployed.
https://tsenaq.db.files.1drv.com/y4mQF0YMhGFr6fhCvkuLHblRMroOkG97QLy4vLmWKfw6hk43gx7t1TaBdtn6E2tYW496DPZOabIiji3RQUUmKBi1tH0XCId9o7u1UVNIdPqUKTmWGUP3CPstZ4WjNONtLBnfXl9GB-YBm6pa_atvz_89nspbVVds1qFACqSIO_5OF-ctT-Zhl_sYWUa32dKGqYZLOmUshl1yViSZNZRAbizEw?width=882&height=771&cropmode=none

This step is the most imporant as it will deploy your complete Azure infrastructure. You might want to override some settings depending on the environment you want to deploy to.
> - resourcegroup "cfpexchange-test"   // The name of the resource group you want to use
> - hostingPlanName "cfpexchange-test" // The name of the hosting plan your App Services will be deployed at
> - administratorLogin "" // The name of your SQL Server administrator
> - administratorLoginPassword "" // The password for your SQL Server administrator
> - databaseName "cfpexchange-test" // The name of the CFP Exchange database you want to use
> - sqlServerName "cfpexchange-test" // The name of the SQL Server where the database will be deployed
> - websiteName "cfpexchange-test" // The name of your App Service for the website
> - AD.TenantId "" // The Tenant you are on (subscription guid) 
> - AD.ObjectId "" // The Object Id (guid) of the application which wants to access Key Vault (the App Service)
> - servicebusNamespace "cfpexchangebus-test" // The name of the service bus we're using
> - vaultName "cfpexchange-test-vault" // The name of the Key Vault we're using
> - FeatureToggle.HostOwnImages true // New feature toggle!
> - templateBaseUri "https://raw.githubusercontent.com/Jandev/CfpExchange/features/extract-images/Deployment/" // Important! This should point to the location where the latest `complete-solution.json` is located
> - storageAccountName "cfpexchangestoragetest" // The name of the storage account
> - functionAppName "cfpexchange-functions" // The name of the App Service for the Function App


2. Deploy the actual website
https://hx8e6q.db.files.1drv.com/y4mYBsoQF-PtciyfmkhgRwBSA6JEZhN1ywBIBSmCJgp_l0vQMcmpYfuOF1GwZqBX-sL8ij4FweKdEDz8GBoc-C1BKzQRrdIMzpohc6ow8EJcJjcbeGCnNNG4xcxj-UMV44dsexDatSwvXvqgzndlRwpFcejuYCv80hWRFr6Ao6xqyKbineJ4JFr8h231_g5XMLkDNoq4kYpuW_Pj4Axx1CjTg?width=884&height=571&cropmode=none

Should be fairly easy. Didn't need to specify anything fancy over here.

3. Deploy the actual Function App
https://hkpcrg.db.files.1drv.com/y4mUTulSZs1nv0fijpa7gmzM-9ijzp1uZSuRGXkWS9PqoFJMe-5NuU1gTgE__zWKmoawVzC3t_7v0b7sNILKC8lTHgyym3MHsIpfwY8A8pFAJRJBPQmP3Zufq-FTSxc2yhuTgjup2ZnzKVMWkn0Ya1BXCfA-cpgm2xv0ZUsMvxa4lxc62QTaIYvMpLk2cTf6-oN-yTLRT6MXMeb3cZiGDZSsw?width=894&height=572&cropmode=none

Should be fairly easy. Didn't need to specify anything fancy over here.



Hope the above helps!

**Comment by Jandev** [comment]
Look on the bright side. Once you get this stuff working, it's worth a couple of blog posts at least!

**Comment by jfversluis** [comment]
Looking awesome! Could you update the README with new settings etc?

**Pull request merged**
